question_data = [
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The music group Daft Punk got their name from a negative review they recieved.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Manchester United won the 2013-14 English Premier League.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The music video to The Buggle's \"Video Killed the Radio Star\" was the first music "
                 "video to broadcast on MTV.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
     "question": "This is the correct spelling of \"Supercalifragilisticexpialidocious\".",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Peyton Manning retired after winning Super Bowl XLIX.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In \"Super Mario Bros.\", the clouds and bushes have the same artwork and are just "
                 "different colors.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in "
                 "Atlanta, Georgia on November 22nd, 1963.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Gosho Aoyama Made This Series: (Detective Conan / Case Closed!)", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
     "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the "
                 "anime Highschool of the Dead.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Centripetal force is an apparent force that acts outward on a body moving around a center, "
                 "arising from the body's inertia.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
     "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the game Dead by Daylight, the killer Michael Myers is referred to as \"The Shape\".",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "One of Barack Obama's United States presidential campaign slogans was \"Yes We "
                 "Can\".",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Cats have whiskers under their legs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "Helen Clark was the 37th Prime Minister of Australia.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
     "question": "The song Scatman's World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Not including false teeth, a human has two sets of teeth in their lifetime.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Slovakia is a member of the European Union.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel \"The Lord of "
                 "The Rings\".",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
